# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8080
  servlet:
    context-path: /witsoft

witsoft:
  img:
    # 产线环境：http://192.168.101.131/
    host: http://192.168.100.139:8080/witsoft/

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0

  datasource:
    db1:
      jdbcUrl: jdbc:mysql://127.0.0.1:3306/iot_weilai?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: root
      driverClassName: com.mysql.cj.jdbc.Driver
    db2:
      jdbcUrl: jdbc:mysql://192.168.1.95:3306/bigdata_iot?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver
      enabled: true
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      #      最小空闲链接数
      minimumIdle: 5
      #      最大链接数
      maximumPoolSize: 50
      #      最大生命周期
      maxLifetime: 180000
      #      最长闲置时间
      idleTimeout: 60000
      #      等待连接池的最大毫秒数
      connectionTimeout: 20000

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.witsoft.weilai.domain

logging:
  config: classpath:logback-spring.xml